applications:
    lb:
        type: nginx
        links: [front1, front2]
        ports:
            80: 80
        custom:
            backends: [front1, front2]

    front1:
        type: apache
        links: [app]
        ports:
            8081: 8081
        volumes:
            /var/www: /var/www
        custom:
            fastCgi: app

    front2:
        type: apache
        links: [app]
        ports:
            8082: 8082
        volumes:
            /var/www: /var/www
        custom:
            fastCgi: app

    app:
        type: php-fpm
        ports:
            9000: 9000
        volumes:
            /var/www: /var/www
